using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace GameHook.WebAPI
{
    public class DefaultSwashbuckleFilter : IDocumentFilter
    {
        public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
        {
            // Hide wwwroot assets from being generated by Swagger UI.

            swaggerDoc.Paths["/"] = null;
            swaggerDoc.Paths["/favicon.ico"] = null;
            swaggerDoc.Paths["/site.css"] = null;
            swaggerDoc.Paths["/dist/gameHookMapperClient.js"] = null;
        }
    }
}
